# Generated by Django 6.0.7 on 2026-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_bio_user_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_membership_paid',
            field=models.BooleanField(default=False),
        ),
    ]
