# Generated by Django 5.0.7 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['price'], 'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
