# Generated by Django 5.0.7 on 2026-09-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='auto_renew',
        ),
    ]
