# Generated by Django 5.0.7 on 2026-07-19 20:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('qr_generated', 'QR Generated'), ('qr_scanned', 'QR Scanned'), ('handover_verified', 'Handover Verified'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='recovery_qr/')),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('handover_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_sessions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_recovery_sessions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_sessions', to='posts.post')),
            ],
            options={
                'verbose_name': 'Recovery Session',
                'verbose_name_plural': 'Recovery Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='recovery.recoverysession')),
            ],
            options={
                'verbose_name': 'Recovery OTP',
                'verbose_name_plural': 'Recovery OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_owner', models.BooleanField(default=False)),
                ('confirmed_by_claimant', models.BooleanField(default=False)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_signature', models.TextField(blank=True, null=True)),
                ('claimant_signature', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='recovery.recoverysession')),
            ],
            options={
                'verbose_name': 'Recovery Confirmation',
                'verbose_name_plural': 'Recovery Confirmations',
            },
        ),
        migrations.CreateModel(
            name='RecoveryVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='recovery.recoverysession')),
            ],
            options={
                'verbose_name': 'Recovery Verification Log',
                'verbose_name_plural': 'Recovery Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
