# Generated by Django 5.0.7 on 2026-09-05 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_add_location_name_remove_reward'),
        ('recovery', '0002_restructure_recovery_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverysession',
            old_name='qr_scanned_at',
            new_name='token_verified_at',
        ),
        migrations.RemoveField(
            model_name='recoverysession',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='recoverysession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('token_generated', 'Token Generated'), ('token_entered', 'Token Entered'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recoverysession',
            index=models.Index(fields=['status'], name='recovery_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverysession',
            index=models.Index(fields=['owner', 'status'], name='recovery_owner_status_idx'),
        ),
    ]
