# Generated by Django 5.0.7 on 2026-09-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_replace_qr_with_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryotp',
            name='session',
        ),
        migrations.DeleteModel(
            name='RecoveryConfirmation',
        ),
        migrations.DeleteModel(
            name='RecoveryOTP',
        ),
    ]
