# Generated by Django 5.0.7 on 2026-09-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverysession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
