# Generated by Django 6.0.7 on 2026-07-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Embedding',
                'verbose_name_plural': 'Post Embeddings',
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_from', to='posts.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='posts.post')),
            ],
            options={
                'verbose_name': 'Match Suggestion',
                'verbose_name_plural': 'Match Suggestions',
                'ordering': ['-similarity_score'],
                'unique_together': {('post', 'matched_post')},
            },
        ),
    ]
