# Generated by Django 5.0.7 on 2026-07-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('posts', '0002_postimage_successstory_trustreport_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchsuggestion',
            name='matched_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_matches', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='matchsuggestion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='matchsuggestion',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
