# Generated by Django 5.0.7 on 2026-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_postembedding_pgvector'),
        ('posts', '0004_add_location_name_remove_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsuggestion',
            name='match_strength',
            field=models.CharField(choices=[('strong', 'Strong Match'), ('possible', 'Possible Match')], default='possible', max_length=10),
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='metadata_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='semantic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='matchsuggestion',
            index=models.Index(fields=['status', '-similarity_score'], name='match_status_score_idx'),
        ),
    ]
