# Generated by Django 5.0.7 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_matchsuggestion_match_strength_and_more'),
        ('posts', '0005_alter_posttag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchsuggestion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.UniqueConstraint(fields=('post', 'matched_post'), name='unique_match_suggestion'),
        ),
    ]
