# Generated by Django 5.0.7 on 2026-08-27 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_campuslocation_is_active_category_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reward_amount',
        ),
        migrations.AddField(
            model_name='post',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'post_type'], name='post_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'status'], name='post_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status'], name='post_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['location', 'status'], name='post_location_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trustreport',
            index=models.Index(fields=['status'], name='report_status_idx'),
        ),
    ]
