# Generated by Django 5.0.7 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_add_location_name_remove_reward'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='postimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('post',), name='unique_primary_image_per_post'),
        ),
        migrations.AddConstraint(
            model_name='posttag',
            constraint=models.UniqueConstraint(fields=('post', 'name'), name='unique_post_tag'),
        ),
    ]
