# Generated by Django 5.0.7 on 2026-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posttag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
    ]
