# Generated by Django 5.0.7 on 2026-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_add_rejected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
