# Generated by Django 5.0.7 on 2026-09-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='matched_post',
            field=models.ForeignKey(blank=True, help_text='The Lost/Found post this item has been matched with through recovery token verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='posts.post', verbose_name='Matched Post'),
        ),
    ]
