# Generated by Django 5.0.7 on 2026-09-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_matched_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_resolved',
        ),
    ]
