# Generated by Django 5.0.7 on 2026-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
