# Generated by Django 5.0.7 on 2026-09-05 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match_found', 'Match Found'), ('membership_expiring', 'Membership Expiring'), ('post_claimed', 'Post Claimed'), ('post_resolved', 'Post Resolved'), ('message', 'Message'), ('system', 'System'), ('recovery_update', 'Recovery Update')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'),
        ),
    ]
